### ISSUE TITLE
[question] - Setting up with Flutter

### ISSUE THREAD

**Issue by rodydavis** [jonahwilliams/jonahwilliams.github.io#4]
![Screen Shot 2020-02-18 at 3 20 05 PM](https://user-images.githubusercontent.com/31253215/74786672-25a40400-5262-11ea-94d5-5813d9ea47a2.png)

Once you have the DDC compiling, how do you get it to point to specific packages like flutter?

Also what about 3rd party pure dart ones like flutter_bloc or provider?

**Comment by rodydavis** [comment]
Here is the console:

```
result 23a7aab8-14b7-4bc5-a376-96a99e674efe
file.dart:260 /.dart_tool/package_config.json
file.dart:260 /.packages
file.dart:260 /flutter_web_sdk/flutter_ddc_sdk.dill
file.dart:260 /lib/main.dart
file.dart:260 /.packages
file.dart:260 app.dill.sources
file.dart:260 app.dill.json
file.dart:260 app.dill.map
frontend_server.dart:509 23a7aab8-14b7-4bc5-a376-96a99e674efe
frontend_server.dart:558 +file:///lib/main.dart
frontend_server.dart:517 23a7aab8-14b7-4bc5-a376-96a99e674efe app.dill 0
frontend_server.dart:819 result 92d1431e-c279-459b-9920-1be7b3244c04
file.dart:260 /lib/main.dart
js_primitives.dart:49 Crash when formatting: [PackageNotFound] Could not resolve the package 'flutter' in 'package:flutter/material.dart'.
Unsupported operation: StdIOUtils._getStdioOutputStream
Unsupported operation: StdIOUtils._getStdioOutputStream
    at Object.wrapException (http://127.0.0.1:5500/compiler.js:2212:17)
    at Object._StdIOUtils__getStdioOutputStream (http://127.0.0.1:5500/compiler.js:10138:15)
    at Object.stdout (http://127.0.0.1:5500/compiler.js:10361:18)
    at Object._computeEnableColors (http://127.0.0.1:5500/compiler.js:15241:32)
    at Object.format (http://127.0.0.1:5500/compiler.js:20384:36)
    at ProcessedOptions.format$3 (http://127.0.0.1:5500/compiler.js:82525:21)
    at ProcessedOptions.report$3$context (http://127.0.0.1:5500/compiler.js:82565:43)
    at ProcessedOptions.report$2 (http://127.0.0.1:5500/compiler.js:82575:19)
    at StaticClosure.UriTranslator__packageUriNotFound (http://127.0.0.1:5500/compiler.js:35624:43)
    at UriTranslator._translatePackageUri$2 (http://127.0.0.1:5500/compiler.js:126581:166)
js_helper.dart:1342 Uncaught Crash when compiling null,
at character offset -1:
Unsupported operation: StdIOUtils._getStdioOutputStream
Unsupported operation: StdIOUtils._getStdioOutputStream
    at Object.wrapException (http://127.0.0.1:5500/compiler.js:2212:17)
    at Object._StdIOUtils__getStdioOutputStream (http://127.0.0.1:5500/compiler.js:10138:15)
    at Object.stdout (http://127.0.0.1:5500/compiler.js:10361:18)
    at Object._computeEnableColors (http://127.0.0.1:5500/compiler.js:15241:32)
    at Object.format (http://127.0.0.1:5500/compiler.js:20384:36)
    at ProcessedOptions.format$3 (http://127.0.0.1:5500/compiler.js:82525:21)
    at ProcessedOptions.report$3$context (http://127.0.0.1:5500/compiler.js:82565:43)
    at ProcessedOptions.report$2 (http://127.0.0.1:5500/compiler.js:82575:19)
    at StaticClosure.UriTranslator__packageUriNotFound (http://127.0.0.1:5500/compiler.js:35624:43)
    at UriTranslator._translatePackageUri$2 (http://127.0.0.1:5500/compiler.js:126581:166)

    at Object.wrapException (http://127.0.0.1:5500/compiler.js:2212:17)
    at Object.format (http://127.0.0.1:5500/compiler.js:20429:17)
    at ProcessedOptions.format$3 (http://127.0.0.1:5500/compiler.js:82525:21)
    at ProcessedOptions.report$3$context (http://127.0.0.1:5500/compiler.js:82565:43)
    at ProcessedOptions.report$2 (http://127.0.0.1:5500/compiler.js:82575:19)
    at StaticClosure.UriTranslator__packageUriNotFound (http://127.0.0.1:5500/compiler.js:35624:43)
    at UriTranslator._translatePackageUri$2 (http://127.0.0.1:5500/compiler.js:126581:166)
    at UriTranslator.translate$2 (http://127.0.0.1:5500/compiler.js:126510:21)
    at UriTranslator.translate$1 (http://127.0.0.1:5500/compiler.js:126514:19)
    at Loader_read_closure.call$0 (http://127.0.0.1:5500/compiler.js:114489:55)
wrapException @ js_helper.dart:1342
call$0 @ async_patch.dart:693
_microtaskLoop @ schedule_microtask.dart:43
_startMicrotaskLoop @ schedule_microtask.dart:52
call$1 @ async_patch.dart:51
invokeClosure @ js_helper.dart:2017
(anonymous) @ js_helper.dart:2049
childList (async)
call$1 @ async_patch.dart:64
_scheduleAsyncCallback @ async_patch.dart:29
_rootScheduleMicrotask @ zone.dart:1187
scheduleMicrotask @ schedule_microtask.dart:139
schedule$1 @ stream_impl.dart:666
_addPending$1 @ stream_impl.dart:326
_sendData$1 @ stream_controller.dart:788
_add$1 @ stream_controller.dart:649
add$1 @ stream_controller.dart:595
call$1 @ web_worker_compiler.dart:118
Primitives_applyFunction @ js_helper.dart:1062
_callDartFunctionFast @ core_patch.dart:85
(anonymous) @ js_patch.dart:520
button.onclick @ index.html:62
```

**Comment by rodydavis** [comment]
I looked into how dart pad was compiling and this looks very similar. The only difference being it uses the google apis package.

https://github.com/dart-lang/dart-pad/blob/master/lib/services/dartservices.dart

I got part of the compiler working with dart2native but crashes when loading external deps

**Comment by rodydavis** [comment]
Do I need to bundle compiled versions of packages I want to compile with the DDC compiler?

Sorry for all the questions, but could you also point me in the right direction?

**Comment by rodydavis** [comment]
Never-mind, figured it out: https://github.com/rodydavis/flutter_compiler

Thanks for this repo! Got me looking in the right places

**Comment by jonahwilliams** [comment]
Nice! Yeah, this only includes the sources for the SDK - but you could update the .packages file and patch in whatever

**Comment by rodydavis** [comment]
OK cool! Thank you

**Comment by jonahwilliams** [comment]
I guess I haven't actually published the sources this is built from, I can do that later tonight. You could do it a bit more manually with the writeFile API:

```
window.writeFile('.packages', '...actual package file...');
... And then all of the referenced sources...
```

**Comment by rodydavis** [comment]
ok sweet, yeah if you could that would be really awesome. 

Also Side note could the compiler also be exported with dart2native?

**Comment by jonahwilliams** [comment]
I don't see why not, but you can't load that in a web browser

**Comment by rodydavis** [comment]
True, I was thinking for desktop side use case. 😎
